# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e179b28830e02b85ae44daa0d34129e5ca87eb10578fc02884c1ba110d4a0d2e0a8d3770956955929fc3bfcbcbcd844de4e0dd0942eb279d2e6f751d9e8e2f5c

test:
  secret_key_base: a9babdc040006b548f25941b43891ebbd1cf2538079e02874406be730cf9cc1860a5ce88deb4ef9c85a3449ef356e3a900f8c80943d2b2aa423d1034e79cee9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
